version: 2
jobs:
    build:
        docker:
            - image: python:3.10
        steps:
            - checkout
            - run:
                name: Build documentation
                command: ./build_tools/circle/build_doc.sh
                timeout: "3600" # seconds
            - store_artifacts:
                path: docs/_build/html
            - add_ssh_keys:
                fingerprints:
                    - "13:8e:b6:7a:d2:8f:a0:4d:56:08:97:f2:c8:9c:10:e9"
            - run:
                name: Deploy documentation
                environment:
                    USERNAME: scaramallion
                    EMAIL: scaramallion@users.noreply.github.com
                command: ./build_tools/circle/push_doc.sh
